// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatYouSay.Data;

#nullable disable

namespace WhatYouSay.Migrations
{
    [DbContext(typeof(WhatYouSayContext))]
    [Migration("20260905103203_SummaryNodeOrdinal")]
    partial class SummaryNodeOrdinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WhatYouSay.Data.NodeReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponderTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "ResponderTokenHash", "Kind")
                        .IsUnique();

                    b.ToTable("NodeReactions");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthTokenHash");

                    b.HasIndex("SurveyId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SummaryId");

                    b.ToTable("SummaryNodes");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryNodeReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ResponseId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AreResponsesPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcceptingResponses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPubliclyListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummariserTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SummariserTokenHash");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("WhatYouSay.Data.NodeReaction", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryNode", "Node")
                        .WithMany("Reactions")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.HasOne("WhatYouSay.Data.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.HasOne("WhatYouSay.Data.Survey", "Survey")
                        .WithMany("Summaries")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryNode", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WhatYouSay.Data.Summary", "Summary")
                        .WithMany("Nodes")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryNodeReference", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryNode", "Node")
                        .WithMany("References")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatYouSay.Data.Response", "Response")
                        .WithMany("References")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Reactions");

                    b.Navigation("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Survey", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
