// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatYouSay.Data;

#nullable disable

namespace WhatYouSay.Migrations
{
    [DbContext(typeof(WhatYouSayContext))]
    [Migration("20260829115929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WhatYouSay.Data.PointReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponderTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PointId", "ResponderTokenHash", "Kind")
                        .IsUnique();

                    b.ToTable("PointReactions");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthTokenHash");

                    b.HasIndex("SurveyId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("SummaryTopics");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopicPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Objectivity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sentiment")
                        .HasColumnType("REAL");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("SummaryTopicPoints");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopicPointResponseReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Intensity")
                        .HasColumnType("REAL");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("ResponseId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AreResponsesPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcceptingResponses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPubliclyListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummariserTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SummariserTokenHash");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("WhatYouSay.Data.PointReaction", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryTopicPoint", "Point")
                        .WithMany("Reactions")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.HasOne("WhatYouSay.Data.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.HasOne("WhatYouSay.Data.Survey", "Survey")
                        .WithMany("Summaries")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopic", b =>
                {
                    b.HasOne("WhatYouSay.Data.Summary", "Summary")
                        .WithMany("Topics")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopicPoint", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryTopic", "Topic")
                        .WithMany("Points")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopicPointResponseReference", b =>
                {
                    b.HasOne("WhatYouSay.Data.SummaryTopicPoint", "Point")
                        .WithMany("References")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatYouSay.Data.Response", "Response")
                        .WithMany("References")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("WhatYouSay.Data.Response", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Summary", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopic", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("WhatYouSay.Data.SummaryTopicPoint", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("References");
                });

            modelBuilder.Entity("WhatYouSay.Data.Survey", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
